services:
    mongo:
        image: mongo:4
        restart: always
        volumes:
            - db:/data/db
        networks:
            - proxy

    coding-buddy:
        build: .
        restart: always
        links:
            - mongo
        env_file: production.env
        networks:
            - proxy

volumes:
    db:

networks:
    proxy:
        name: proxy
        external: true
