services:
    mongo:
        image: mongo:4
        volumes:
            - db:/data/db

    app:
        build:
            context: .
            dockerfile: Dockerfile.local
        links:
            - mongo
        ports:
            - 3000:3000
        volumes:
            - ./dist:/app/dist
            - ./node_modules:/app/node_modules
        env_file: local.env

volumes:
    db: